Sub TerminateResponsibility()

Call Menu_IMHardwareStaffMenuOption


End Sub
Sub Menu_IMHardwareStaffMenuOption()
' Generated by the Reflection Macro Recorder on 04-06-2023 13:33:44.27.
' Generated by Micro Focus Reflection Desktop Pro (x64) (16.2.882.0).

Dim osCurrentScreen As screen
Dim osCurrentTerminal As Terminal
Dim returnValue As Integer



Const NEVER_TIME_OUT = 0

Dim LF As String    ' Chr(rcLF) = Chr(10) = Control-J
Dim CR As String    ' Chr(rcCR) = Chr(13) = Control-M

Set osCurrentTerminal = ThisFrame.SelectedView.control
Set osCurrentScreen = osCurrentTerminal.screen

LF = Chr(10)
CR = Chr(13)

osCurrentScreen.SendKeys "^IT Equipment Responsibility Option"
osCurrentScreen.SendControlKey ControlKeyCode_Return
'Wait for Select IT Equipment Responsibility Option:
returnValue = osCurrentScreen.WaitForString3(LF & "Select IT Equipment Responsibility Option: ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If
ThisFrame.StatusBarText = ""

osCurrentScreen.SendKeys "Terminate Responsibility"
osCurrentScreen.SendControlKey ControlKeyCode_Return
'Wait for a Specify method for selecting IT assignments:
returnValue = osCurrentScreen.WaitForString3(LF & "Specify method for selecting IT assignments: ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If
ThisFrame.StatusBarText = ""

osCurrentScreen.SendKeys "E"
osCurrentScreen.SendControlKey ControlKeyCode_Return
'Wait for a Select EQUIPMENT ENTRY #:
returnValue = osCurrentScreen.WaitForString3(LF & "Select EQUIPMENT ENTRY #: ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If

ThisFrame.StatusBarText = "DOnE"