Sub CreateVistaPrinter()

Call Menu_IMHardwareStaffMenuOption


End Sub
Sub Menu_IMHardwareStaffMenuOption()
' Generated by the Reflection Macro Recorder on 04-06-2023 13:33:44.27.
' Generated by Micro Focus Reflection Desktop Pro (x64) (16.2.882.0).

Dim osCurrentScreen As Screen
Dim osCurrentTerminal As Terminal
Dim returnValue As Integer



Const NEVER_TIME_OUT = 0

Dim LF As String    ' Chr(rcLF) = Chr(10) = Control-J
Dim CR As String    ' Chr(rcCR) = Chr(13) = Control-M

Set osCurrentTerminal = ThisFrame.SelectedView.control
Set osCurrentScreen = osCurrentTerminal.Screen

LF = Chr(10)
CR = Chr(13)

'Wait for Select IM Hardware Staff Menu Option: or go ^
returnValue = osCurrentScreen.WaitForString3(LF & "Select IM Hardware Staff Menu Option: ", 1000, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    osCurrentScreen.SendKeys "^IM Hardware Staff"
    osCurrentScreen.SendControlKey ControlKeyCode_Return
End If
ThisFrame.StatusBarText = ""

'Wait for Select IM Hardware Staff Menu Option: or go ^
returnValue = osCurrentScreen.WaitForString3(LF & "Select IM Hardware Staff Menu Option: ", 1000, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    osCurrentScreen.SendKeys "^IM Hardware Staff"
    osCurrentScreen.SendControlKey ControlKeyCode_Return
    ThisFrame.StatusBarText = "Line Break 41"
End If

'Wait for Select IM Hardware Staff Menu Option: or go ^
returnValue = osCurrentScreen.WaitForString3(LF & "Select IM Hardware Staff Menu Option: ", 1000, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    osCurrentScreen.SendKeys "^IM Hardware Staff"
    osCurrentScreen.SendControlKey ControlKeyCode_Return
    ThisFrame.StatusBarText = "Line Break 49"
End If

'Wait for Select IM Hardware Staff Menu Option:
ThisFrame.StatusBarText = "Line Break 53"
returnValue = osCurrentScreen.WaitForString3(LF & "Select IM Hardware Staff Menu Option: ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If
ThisFrame.StatusBarText = ""

'Wait for Select VA FileMan Option:
osCurrentScreen.SendKeys "^VA FILEMAN"
osCurrentScreen.SendControlKey ControlKeyCode_Return
ThisFrame.StatusBarText = "Line Break 63"
returnValue = osCurrentScreen.WaitForString3(LF & "Select VA FileMan Option: ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If
ThisFrame.StatusBarText = ""

'Wait for Input to what File: DEVICE//
osCurrentScreen.SendKeys "Enter"
osCurrentScreen.SendControlKey ControlKeyCode_Return
ThisFrame.StatusBarText = "Line Break 73"
returnValue = osCurrentScreen.WaitForString3(LF & "Input to what File: DEVICE// ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If
ThisFrame.StatusBarText = ""

'Press enter and Wait for EDIT WHICH FIELD: ALL// :
osCurrentScreen.SendControlKey ControlKeyCode_Return
ThisFrame.StatusBarText = "Line Break 82"
returnValue = osCurrentScreen.WaitForString3(LF & "EDIT WHICH FIELD: ALL// ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If
ThisFrame.StatusBarText = ""

'Press Enter and Wait for a Select DEVICE NAME:
osCurrentScreen.SendControlKey ControlKeyCode_Return
ThisFrame.StatusBarText = "Line Break 91"
returnValue = osCurrentScreen.WaitForString3(LF & "Select DEVICE NAME: ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If
ThisFrame.StatusBarText = ""

'Prefill device name, have user hit Enter and wait for DEVICE LOCATION OF TERMINAL:
osCurrentScreen.SendKeys "LEX-DPSURGD113"
ThisFrame.StatusBarText = "Type the device name,STRIKE enter and answer Y to next prompt"
returnValue = osCurrentScreen.WaitForString3(LF & "   DEVICE LOCATION OF TERMINAL: ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If
ThisFrame.StatusBarText = ""

'Prefill a location, have user hit Enter and wait for    DEVICE $I: 
osCurrentScreen.SendKeys "Bowling D113"
ThisFrame.StatusBarText = "Enter location of Printer like: BLDG 17 RM 026 and STRIKE enter"
returnValue = osCurrentScreen.WaitForString3(LF & "   DEVICE $I: ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If
ThisFrame.StatusBarText = ""

'Prefill a Device $I, have user hit Enter and wait for   DEVICE VOLUME SET(CPU): 
osCurrentScreen.SendKeys "LEX_PQ$:LEX-DPSURGD113.TXT"
ThisFrame.StatusBarText = "Replace the number with the IP while levaeing the X between octets. Then STRIKE enter"
returnValue = osCurrentScreen.WaitForString3(LF & "   DEVICE VOLUME SET(CPU): ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If
ThisFrame.StatusBarText = ""

'Send Enter key to advance past DEVICE VOLUME SET(CPU): and wait on    DEVICE TYPE:  
osCurrentScreen.SendControlKey ControlKeyCode_Return
ThisFrame.StatusBarText = "Line Break 127"
returnValue = osCurrentScreen.WaitForString3(LF & "   DEVICE TYPE: ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If
ThisFrame.StatusBarText = ""

'Set Device type to HFS
osCurrentScreen.SendKeys "HFS"
osCurrentScreen.SendControlKey ControlKeyCode_Return

'Confirm and advance past XLOCATION OF TERMINAL:
osCurrentScreen.SendControlKey ControlKeyCode_Return

'Wait for Select MNEMONIC: 
ThisFrame.StatusBarText = "Line Break 142"
returnValue = osCurrentScreen.WaitForString3(LF & "Select MNEMONIC: ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If

'Prefill device name, have user hit Enter and wait for second Select MNEMONIC: 
ThisFrame.StatusBarText = "Input Windows Printer name like: LEX-DPIMS009"
osCurrentScreen.SendKeys "LEX-DPSURGD113"

'Advance past second MNEWMONIC:
returnValue = osCurrentScreen.WaitForString3(LF & "Select MNEMONIC: ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If
ThisFrame.StatusBarText = ""

'Go to SUBTYPE menu
osCurrentScreen.SendKeys "^SUBTYPE"
osCurrentScreen.SendControlKey ControlKeyCode_Return
ThisFrame.StatusBarText = "Line Break 162"
returnValue = osCurrentScreen.WaitForString3(LF & "SUBTYPE: ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If

'Prefill subtype and STRIKE return
ThisFrame.StatusBarText = "Just one common example of the subtype (AKA: driver) used"
osCurrentScreen.SendKeys "P-TCP96HPLASER"
osCurrentScreen.SendControlKey ControlKeyCode_Return

'Wait for CHOOSE 1-4: and choose 1 
ThisFrame.StatusBarText = "Line Break 174"
returnValue = osCurrentScreen.WaitForString3(LF & "CHOOSE 1-4: ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If
ThisFrame.StatusBarText = ""
osCurrentScreen.SendKeys "1"
osCurrentScreen.SendControlKey ControlKeyCode_Return

'Wait for ASK DEVICE: 
ThisFrame.StatusBarText = "Line Break 174"
returnValue = osCurrentScreen.WaitForString3(LF & "ASK DEVICE: ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If
ThisFrame.StatusBarText = ""

'Go to QUEUING Menu  
osCurrentScreen.SendKeys "^QUEUING"
osCurrentScreen.SendControlKey ControlKeyCode_Return

'Wait till atQUEUING Menu  
ThisFrame.StatusBarText = "Line Break 196"
returnValue = osCurrentScreen.WaitForString3(LF & "QUEUING: ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If
ThisFrame.StatusBarText = ""

'Sned F to chose FORCE option  
osCurrentScreen.SendKeys "F"
osCurrentScreen.SendControlKey ControlKeyCode_Return

'Wait for OUT-OF-SERVICE DATE:  
ThisFrame.StatusBarText = "Line Break 208"
returnValue = osCurrentScreen.WaitForString3(LF & "OUT-OF-SERVICE DATE: ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If
ThisFrame.StatusBarText = ""

'Go to OPEN PARAMETERS Menu
osCurrentScreen.SendKeys "^OPEN PARAMETERS"
osCurrentScreen.SendControlKey ControlKeyCode_Return

'Wait for OPEN PARAMETERS Menu
ThisFrame.StatusBarText = "Line Break 220"
returnValue = osCurrentScreen.WaitForString3(LF & "OPEN PARAMETERS: ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If
ThisFrame.StatusBarText = ""

'Send NWS in quotes , wait for USER to hit enter and wait for CLOSE PARAMETERS:
osCurrentScreen.SendKeys """NWS"""
ThisFrame.StatusBarText = """The open and close quotes are required ""NWU"" if it is an Intermec. STRIKE Enter after done"""
returnValue = osCurrentScreen.WaitForString3(LF & "CLOSE PARAMETERS: ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If
ThisFrame.StatusBarText = ""

'Go to ^PRINT SERVER NAME OR ADDRESS Menu
osCurrentScreen.SendKeys "^PRINT SERVER NAME OR ADDRESS"
osCurrentScreen.SendControlKey ControlKeyCode_Return

'Wait for PRINT SERVER NAME OR ADDRESS Menu
ThisFrame.StatusBarText = "Line Break 241"
returnValue = osCurrentScreen.WaitForString3(LF & "PRINT SERVER NAME OR ADDRESS: ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If
ThisFrame.StatusBarText = ""

'Send IM and wait for User to STRIKE enter, then wait for TELNET PORT: #I used LEX-PT110151 for DHCP printer
osCurrentScreen.SendKeys "10.74.42.20"
ThisFrame.StatusBarText = "Please enter IP and STRIKE enter"
returnValue = osCurrentScreen.WaitForString3(LF & "TELNET PORT: ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If
ThisFrame.StatusBarText = ""

'Send 9100 and wait for REMOTE PRINTER NAME: 
osCurrentScreen.SendKeys "9100"
osCurrentScreen.SendControlKey ControlKeyCode_Return
ThisFrame.StatusBarText = "Line Break 232"
returnValue = osCurrentScreen.WaitForString3(LF & "REMOTE PRINTER NAME: ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If
ThisFrame.StatusBarText = ""

'Move close to root
osCurrentScreen.SendKeys "^"
osCurrentScreen.SendControlKey ControlKeyCode_Return
ThisFrame.StatusBarText = "Line Break 270"
returnValue = osCurrentScreen.WaitForString3(LF & "Select DEVICE NAME: ", NEVER_TIME_OUT, WaitForOption.WaitForOption_AllowKeystrokes)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 11001, "WaitForString3", "Timeout waiting for string.", "VBAHelp.chm", "11001"
End If
ThisFrame.StatusBarText = "Vista Printer Created"

End Sub