#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  Apr 17, 2023 01:28:27 PM EDT  platform: Darwin
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 752x505+420+150
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1440 789
    wm minsize $top 72 15
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::style configure Frame -background $vTcl(actual_gui_bg)
    ttk::style configure Frame -foreground $vTcl(actual_gui_fg)
    ttk::style configure Frame -font "$vTcl(actual_gui_font_dft_desc)"
    frame "$top.fra47" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 365 -width 435 
    vTcl:DefineAlias "$top.fra47" "Frame1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.fra47
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list selected $vTcl(actual_gui_bg) active $vTcl(tabbg1) !active $vTcl(tabbg2)]
    ttk::style map TNotebook.Tab -foreground [list selected $vTcl(actual_gui_fg) active $vTcl(tabfg1) !active $vTcl(tabfg2)]
    ttk::notebook "$site_3_0.tNo48" \
        -width 434 -height 364 -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tNo48" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Frame -background $vTcl(actual_gui_bg)
    ttk::style configure Frame -foreground $vTcl(actual_gui_fg)
    ttk::style configure Frame -font "$vTcl(actual_gui_font_dft_desc)"
    frame "$site_3_0.tNo48.t0" \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.tNo48.t0" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $site_3_0.tNo48 add $site_3_0.tNo48.t0 \
        -padding 0 -sticky nsew -state normal -text "Page 1" -image {} \
        -compound left -underline -1 
    set site_5_0  $site_3_0.tNo48.t0
    ttk::style configure Frame -background $vTcl(actual_gui_bg)
    ttk::style configure Frame -foreground $vTcl(actual_gui_fg)
    ttk::style configure Frame -font "$vTcl(actual_gui_font_dft_desc)"
    frame "$site_3_0.tNo48.t1" \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.tNo48.t1" "TNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $site_3_0.tNo48 add $site_3_0.tNo48.t1 \
        -padding 0 -sticky nsew -state normal -text "Page 2" -image {} \
        -compound left -underline -1 
    set site_5_1  $site_3_0.tNo48.t1
    place $site_3_0.tNo48 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.998 -height 0 \
        -relheight 0.997 -anchor nw -bordermode ignore 
    ttk::style configure TSeparator -background $vTcl(actual_gui_bg)
    ttk::style configure TSeparator -foreground $vTcl(actual_gui_fg)
    ttk::style configure TSeparator -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::separator "$top.tSe49" \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe49" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TPanedwindow -background $vTcl(actual_gui_bg)
    ttk::style configure TPanedwindow -foreground $vTcl(actual_gui_fg)
    ttk::style configure TPanedwindow -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TPanedwindow -background $vTcl(actual_gui_bg)
    ttk::style configure TPanedwindow.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TPanedwindow.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TPanedwindow.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::panedwindow "$top.tPa50" \
        -orient horizontal 
    vTcl:DefineAlias "$top.tPa50" "TPanedwindow1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe "$top.tPa50.p1" \
        -text "Pane 1" -width 75 -height 200 
    vTcl:DefineAlias "$top.tPa50.p1" "TPanedwindow1_p1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_4_0 $top.tPa50.p1
    $top.tPa50 add $top.tPa50.p1 
    $top.tPa50 pane $top.tPa50.p1 -weight 0
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe "$top.tPa50.p2" \
        -text "Pane 2" -width 125 -height 200 
    vTcl:DefineAlias "$top.tPa50.p2" "TPanedwindow1_p2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_4_1 $top.tPa50.p2
    $top.tPa50 add $top.tPa50.p2 
    $top.tPa50 pane $top.tPa50.p2 -weight 0
$site_4_0 configure -width 75
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra47 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.111 -width 0 -relwidth 0.725 \
        -height 0 -relheight 0.811 -anchor nw -bordermode ignore 
    place $top.tSe49 \
        -in $top -x 0 -relx 0.75 -y 0 -rely 0.111 -width 0 -relwidth 0.002 \
        -height 0 -relheight 0.889 -anchor nw -bordermode ignore 
    place $top.tPa50 \
        -in $top -x 0 -relx 0.85 -y 0 -rely 0.444 -width 0 -relwidth 0.342 \
        -height 0 -relheight 0.444 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

